#!/bin/bash

#SBATCH --job-name=testtipping
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=64
#SBATCH --array=0-1
#SBATCH --time=00:10:00
#SBATCH --partition=rome
#SBATCH --mail-type=BEGIN,END,FAIL,TIME_LIMIT_80
#SBATCH -o ./logs/out/TEST%A_%a.out 
#SBATCH -e ./logs/error/TEST%A_%a.out
#SBATCH --mail-user=a.titton@uva.nl

module load 2023
module load Julia/1.9.2-linux-x86_64

cd $HOME/scc-tipping-points # Move to base directory
mkdir -p "$TMPDIR"/data # Create scratch directory with user name
rsync data/calibration.jld2 "$TMPDIR"/data # Copy calibration data to scratch

# Extract parameters at the SLURM_ARRAY_TASK_ID from parameters.json
jq_command='
.benchmarkparameters[$id | tonumber] | 
"--rra \(.rra) --eis \(.eis)" +
(if .leveldamages then " --leveldamages" else "" end) +
(if .allownegative then " --allownegative" else "" end)
'

params=$(jq -r --arg id "$SLURM_ARRAY_TASK_ID" "$jq_command" jobs/simulations/parameters.json)

# Run script
julia --threads 64 --project scripts/runbenchmark.jl \
    -d "data" -s "simulation-test" --verbose 2 --overwrite \
    -N 11 $params

# Copy results back to home
rsync -avzu "$TMPDIR"/data $HOME/scc-tipping-points