#!/bin/bash

#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=64
#SBATCH --time=00:10:00
#SBATCH --partition=rome
#SBATCH --job-name=tipping-points-test
#SBATCH --mail-type=BEGIN,END,FAIL,TIME_LIMIT_50,TIME_LIMIT_80,TIME_LIMIT_90
#SBATCH --mail-user=a.titton@uva.nl

module purge
module load 2023
module load Julia/1.9.2-linux-x86_64

cd $HOME/scc-tipping-points # Move to base directory
mkdir -p "$TMPDIR" # Create scratch directory with user name
cp -r data "$TMPDIR"/data # Copy data to scratch

# Run script 
julia --project scripts/runbenchmark.jl \
    -N 11 -p 63 \
    -d "data" -s "test-simulation" \
    --verbose 1 --overwrite

# Copy results back to home
cp -r "$TMPDIR"/data/test-simulation $HOME/scc-tipping-points/data/test-simulation