#!/bin/bash

#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=64
#SBATCH --time=00:20:00
#SBATCH --partition=rome
#SBATCH --job-name=tipping-points-test
#SBATCH --mail-type=BEGIN,END,FAIL,TIME_LIMIT_50,TIME_LIMIT_80,TIME_LIMIT_90
#SBATCH --mail-user=a.titton@uva.nl

module purge
module load 2023
module load julia

# Base directory
# TODO: Copy and paste from scratch 
cd $HOME/scc-tipping-points

mkdir -p /scratch-shared/$USER

# Run script 
julia --project scripts/runoptimal.jl \
    -N 11 -p 64 \
    -d "data" -s "test-simulation" \
    --verbose 1 --overwrite