#!/bin/bash

#SBATCH --job-name=tipping-test
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=20
#SBATCH --time=00:10:00
#SBATCH --partition=rome
#SBATCH --mail-type=BEGIN,END,FAIL,TIME_LIMIT_80
#SBATCH -o ./logs/out/JOB%j.out 
#SBATCH -e ./logs/error/JOB%j.out
#SBATCH --mail-user=a.titton@uva.nl

module purge
module load 2023
module load Julia/1.9.2-linux-x86_64

cd $HOME/scc-tipping-points # Move to base directory
mkdir -p $TMPDIR/data # Create scratch directory with user name
rsync data/calibration.jld2 $TMPDIR/data # Copy calibration data to scratch

# Run script 
julia --project scripts/runoptimal.jl \
    -d "data" -s "simulation" --verbose 1 --overwrite \
    -N 31 -p 19 \
    --rra 10 --eis 0.75 --threshold 2.5

# Copy results back to home
rsync -ru $TMPDIR/data/simulation $HOME/scc-tipping-points/data