#!/bin/bash

#SBATCH --job-name=test
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --array=0-2
#SBATCH --time=00:30:00
#SBATCH --partition=rome
#SBATCH --mail-type=BEGIN,END,FAIL,TIME_LIMIT_80
#SBATCH -o ./logs/out/TEST%A_%a.out 
#SBATCH -e ./logs/error/TEST%A_%a.out
#SBATCH --mail-user=a.titton@uva.nl

module load 2024
module load Julia/1.10.4-linux-x86_64

cd $HOME/scc-tipping-points # Move to base directory

SCRATCHDATA="$TMPDIR"/data
mkdir -p $SCRATCHDATA # Create scratch directory with user name
rsync data/calibration $SCRATCHDATA # Copy calibration data to scratch

# Extract parameters at the SLURM_ARRAY_TASK_ID from parameters.json
jq_command='
.parameters[$id | tonumber] | 
"--threshold \(.threshold) --damages \(.damage)" +
(if .withnegative then " --withnegative" else "" end)
'

params=$(jq -r --arg id "$SLURM_ARRAY_TASK_ID" "$jq_command" jobs/planner/parameters.json)

# Run script 
julia --threads "auto" --project scripts/solve.jl --NT 31 --Nm 31 \
    --cachestep 0.5 --verbose 1 --tol 0.001 --dt 0.01 \
    --datapath "$SCRATCHDATA"  --simulationpath "simulation-test" --overwrite \
    $params

# Copy results back to home
rsync -avzu $SCRATCHDATA $HOME/scc-tipping-points
rm -r $SCRATCHDATA # Remove scratch directory